twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/public/images': images
        '%kernel.project_dir%/assets/styles': styles

when@test:
    twig:
        strict_variables: true
